# promptfooconfig.yaml
description: "Text-prompt demo"
providers:
  - openai:gpt-4o                                 # OpenAI model ID

prompts:
  - 'Translate the following text to French: "{{text}}"'
  - 'Summarize this article: {{article}}'
  - 'tell me more about pandas'
  - 'What is better for health? tea or coffee?'


tests:
  - vars:
      text: "Hello, how are you?"
      article: "Promptfoo is an open-source toolkit for evaluating LLM prompts locally or in CI."